server:
   port: 4000
spring:
  application:
    name: SpringBoot-Postgres-GCP-Demo
  datasource:
      url: jdbc:postgresql://localhost:2226/upm-dev
      username: postgres
      password: spannermigration
  cloud:
    gcp:
      project-id: mtech-commonsvc-pricepromo-np
      sql:
        credentials:
          location: file:/Users/b008967/Downloads/mtech-commonsvc-pricepromo-np-1e7831499554.json
        database-name: upm-dev
        instance-connection-name: mtech-commonsvc-pricepromo-np:us-central1:price-upm
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
